### ISSUE TITLE
Arbitrarily code execute

### ISSUE THREAD

**Issue by IanSmith123** [prasmussen/glot-code-runner#15]
This program doesn't limit the execution of command, we can run arbitrarily command on this runner.

payload:
```
{
  "language": "python",
  "files": [
    {
      "name": "main.py",
      "content": "import os\nos.system('touch /tmp/pwned')"
    }
  ]
}
```
output:
```
# ./runner
{
  "language": "python",
  "files": [
    {
      "name": "main.py",
      "content": "import os\nos.system('touch /tmp/pwned')"
    }
  ]
}
{"stdout":"","stderr":"","error":""}
# ls |grep pwn
pwned
```
 If this program run on a website,  it will cause remote command execution.

For example
![image](https://user-images.githubusercontent.com/19611084/44516170-f0fbce80-a6f6-11e8-8d36-78d0939aba12.png)

**Comment by prasmussen** [comment]
Indeed, this tool does not limit what can be run. You should only run this inside a container or similar. glot.io uses this inside [glot-containers](https://github.com/prasmussen/glot-containers) for sandboxing and the container is deleted after each run.
