### ISSUE TITLE
Add R (statistical computing)

### ISSUE THREAD

**Issue by timflutre** [prasmussen/glot-code-runner#3]
Hello, if I would like to add [R](https://www.r-project.org/), what should I do?

**Comment by prasmussen** [comment]
I've added some instructions on how to add a new language here: [https://github.com/prasmussen/glot/wiki/Instructions-for-adding-a-new-language-to-glot.io](https://github.com/prasmussen/glot/wiki/Instructions-for-adding-a-new-language-to-glot.io)

**Comment by timflutre** [comment]
Thanks!
