### ISSUE TITLE
Changing relative import to absolute import

### ISSUE THREAD

**Issue by maddyonline** [prasmussen/glot-code-runner#8]
Currently many imports used are relative. This prevents from using tools like go get. Of course, one can build the binary by using `go build github.com/prasmussen/glot-code-runner/runner.go`. But for working on fork, it seems it would be useful if imports are fully qualified. Is there a reason for not preferring this style?

**Comment by prasmussen** [comment]
No reason other than laziness. I will accept pull request for change to fully qualified imports.
